; Script generated by the Antigravity AI assistant.
; Inno Setup configuration script for ControlSense Tracker.

#define MyAppName "CM Attendance"
#define MyAppVersion "1.2.0"
#define MyAppPublisher "CM"
#define MyAppExeName "CMAttendance.exe"

[Setup]
AppId={{5F7C1848-8C39-4BC9-9A7B-9A7B4EDA1848}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
; Install to user AppData so it does NOT require administrator rights
DefaultDirName={userappdata}\{#MyAppName}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir=Output
OutputBaseFilename=CMAttendance_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startup"; Description: "Run CM Attendance automatically on Windows startup"; GroupDescription: "Startup options:"

[Files]
Source: "dist\CMAttendance_Release\CMAttendance.exe"; DestDir: "{app}"; Flags: ignoreversion
; Note: config.json is already baked into the .exe by PyInstaller

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "CMAttendance"; ValueData: """{app}\{#MyAppExeName}"""; Flags: uninsdeletevalue; Tasks: startup

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
